apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nvidia-driver
  namespace: "harvester-system"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nvidia-driver
subjects:
  - kind: ServiceAccount
    name: nvidia-driver
    namespace: "harvester-system"
